global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'plane_services'
    static_configs:
      - targets:
          - 'plane-db:5432'
          - 'plane-redis:6379'
          - 'plane-mq:5672'
          - 'api:8000'
          - 'web:80'

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['100.24.85.118:9100']

